const indianPlayers = [
    {
        playerName: "Virat Kohli",
        teamName: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Rohit Sharma",
        teamName: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Hardik Pandya",
        teamName: "India",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Jasprit Bumrah",
        teamName: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        playerName: "Mohammed Shami",
        teamName: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        playerName: "Ravindra Jadeja",
        teamName: "India",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Left Hand Bat",
        bowlingStyle: "Left Arm Medium"
    }, {
        playerName: "Mohammed Siraj",
        teamName: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        playerName: "Shreyas Iyer",
        teamName: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Ravichandran Ashwin",
        teamName: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Suryakumar Yadav",
        teamName: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Shubman Gill",
        teamName: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        playerName: "Mahendra Singh Dhoni",
        teamName: "India",
        role: "Wicket Keeper Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }
]

const pakistaniPlayers = [
    {
        playerName: "Babar Azam",
        teamName: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Fakhar Zaman",
        teamName: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Mohammad Rizwan",
        teamName: "Pakistan",
        role: "Wicket Keeper Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Mohammad Hafeez",
        teamName: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        playerName: "Mohammad Amir",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        playerName: "Shaheen Afridi",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        playerName: "Mohammad Hasnain",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    },{
        playerName: "Shadab Khan",
        teamName: "Pakistan",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        playerName: "Mohammad Nawaz",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        playerName: "Haris Rauf",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    },{
        playerName: "Mohammad Wasim",
        teamName: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        runs: 0,
        runsGiven: 0,
        fours: 0,
        sixes: 0,
        haveDotBalls: 0,
        wickets: 0,
        overBowled:0,
        ballPlayed:0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }
]

export { indianPlayers, pakistaniPlayers }