const indianPlayers = [
    {
        name: "Virat Kohli",
        team: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Rohit Sharma",
        team: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Hardik Pandya",
        team: "India",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Jasprit Bumrah",
        team: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        name: "Mohammed Shami",
        team: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        name: "Ravindra Jadeja",
        team: "India",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Left Hand Bat",
        bowlingStyle: "Left Arm Medium"
    }, {
        name: "Mohammed Siraj",
        team: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        name: "Shreyas Iyer",
        team: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Ravichandran Ashwin",
        team: "India",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Suryakumar Yadav",
        team: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Shubman Gill",
        team: "India",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        name: "Mahendra Singh Dhoni",
        team: "India",
        role: "Wicket Keeper Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }
]

const pakistaniPlayers = [
    {
        name: "Babar Azam",
        team: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Fakhar Zaman",
        team: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Mohammad Rizwan",
        team: "Pakistan",
        role: "Wicket Keeper Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Mohammad Hafeez",
        team: "Pakistan",
        role: "Batsman",
        isBatsman: true,
        isBowler: false,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    }, {
        name: "Mohammad Amir",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        name: "Shaheen Afridi",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }, {
        name: "Mohammad Hasnain",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    },{
        name: "Shadab Khan",
        team: "Pakistan",
        role: "All Rounder",
        isBatsman: true,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        name: "Mohammad Nawaz",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Medium"
    },{
        name: "Haris Rauf",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    },{
        name: "Mohammad Wasim",
        team: "Pakistan",
        role: "Bowler",
        isBatsman: false,
        isBowler: true,
        maiden: 0,
        haveRuns: 0,
        giveRuns: 0,
        haveFours: 0,
        haveSixes: 0,
        haveDotBalls: 0,
        haveWickets: 0,
        battingStyle: "Right Hand Bat",
        bowlingStyle: "Right Arm Fast"
    }
]

export { indianPlayers, pakistaniPlayers }